# Generated by Django 3.2.5 on 2021-07-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_products_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_name',
            field=models.CharField(max_length=30),
        ),
    ]
