# Generated by Django 3.2.5 on 2021-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_products_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
