# Generated by Django 3.2.5 on 2021-07-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_auto_20210720_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='images/broken/broken.png', upload_to='images/'),
        ),
    ]
