# Generated by Django 3.2.5 on 2021-07-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0007_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='product_pic',
        ),
    ]
